name: Mirror to BitBucket (local)
on: []

jobs:
  mirror-to-bitbucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # <-- clone with complete history
      - name: Push
        uses: ./ # Uses an action in the root directory
        id: mirror-to-bitbucket
        with:
          password: ${{ secrets.BITBUCKET_PASSWORD }}
